// build-css — Tailwind 4 + daisyUI 5 turns ui/workbench/app/globals.css into
// one TS string for report.html (core is pure: no disk read at run time).
// The built sheet itself is a scratch file, not a committed output — only
// report-css.ts is committed, like dist/.
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
// Tailwind 4's native module (@tailwindcss/oxide) needs Node 20+. On an
// older Node the committed report-css.ts stands; CI's Node 22 and 24 legs
// rebuild it and fail on a stale copy.
if (Number(process.versions.node.split(".")[0]) < 20) {
  process.stdout.write("build:css: skipped, needs Node 20+; the committed sheet stands.\n");
  process.exit(0);
}
const input = path.join(root, "ui", "workbench", "app", "globals.css");
const scratch = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "cw-build-css-")), "app.css");
execFileSync(path.join(root, "node_modules", ".bin", "tailwindcss"), ["-i", input, "-o", scratch, "--minify"], { cwd: root, stdio: "inherit" });
const css = fs.readFileSync(scratch, "utf8");
fs.rmSync(path.dirname(scratch), { recursive: true, force: true });
fs.writeFileSync(
  path.join(root, "src", "core", "format", "report-css.ts"),
  `// Generated by npm run build:css from ui/workbench/app/globals.css; do not edit.\nexport const REPORT_CSS = ${JSON.stringify(css)};\n`
);
