// build-css — Tailwind 4 + daisyUI 5 turns ui/workbench/app.src.css into ui/workbench/app.css,
// then the same sheet becomes one TS string for report.html (core is pure:
// no disk read at run time). Both outputs are committed, like dist/.
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
// Tailwind 4's native module (@tailwindcss/oxide) needs Node 20+. On an
// older Node the committed sheet stands; CI's Node 22 and 24 legs rebuild
// it and fail on a stale copy.
if (Number(process.versions.node.split(".")[0]) < 20) {
  process.stdout.write("build:css: skipped, needs Node 20+; the committed sheet stands.\n");
  process.exit(0);
}
const css = path.join(root, "ui", "workbench", "app.css");
execFileSync(path.join(root, "node_modules", ".bin", "tailwindcss"), ["-i", path.join(root, "ui", "workbench", "app.src.css"), "-o", css, "--minify"], { cwd: root, stdio: "inherit" });
fs.writeFileSync(
  path.join(root, "src", "core", "format", "report-css.ts"),
  `// Generated by npm run build:css from ui/workbench/app.css; do not edit.\nexport const REPORT_CSS = ${JSON.stringify(fs.readFileSync(css, "utf8"))};\n`
);
