#!/usr/bin/env node
"use strict";

// release-flow.js — portable, vendor-neutral release orchestrator.
//
// One script that runs the SAME gated release flow under any harness
// (Claude / Codex / Gemini / OpenCode) or a plain shell. It does NOT depend on
// any one host's agent-orchestration primitive — it is just node + git + the
// existing CW scripts. The only LLM step (the independent reviewer) is
// DELEGATED through CW's agent backend config (CW_AGENT_COMMAND / CW_AGENT_ENDPOINT),
// so whichever model you configure does the review. CW spawns the agent
// argv-style (shell:false), inherits the agent's own env/key, and imports no
// model SDK — the same red line as src/execution-backend.ts.
//
// Modes:
//   node release-flow.js [--check]                 gate + review, no mutation (default)
//   node release-flow.js --cut --version x.y.z [--push]
//                                                  preflight (fail-fast checks BEFORE the
//                                                  gate/vendor/reviewer spend anything),
//                                                  then gate + review, then bump:version,
//                                                  commit verdict, tag, and — when --push —
//                                                  push ONLY the tag (refs/tags/vx.y.z; the
//                                                  verdict commit is a one-hop leaf off the
//                                                  reviewed main tip, it never lands on a
//                                                  branch) and create the GitHub Release
//                                                  (idempotent; opt out with --no-release)
//   node release-flow.js --release --version x.y.z create-or-skip the GitHub Release for an
//                                                  already-pushed tag (backfill); no gate/cut.
//                                                  Fails closed if gh can't create it; add
//                                                  --soft for best-effort (skip-not-fail).
// Flags also accepted: --prev-tag <t>, --agent-command "...", --agent-model m, --dry-run,
//   --preflight-only (run the cut preflight and stop — used by release-oneclick.js),
//   --allow-stale-head (skip the HEAD == origin/main tip check, deliberate re-cuts only)
//
// VERDICT CONTRACT (auto-generated by --cut, never write by hand):
//   Path:  .cw-release/review-<FULLSHA>.verdict
//   First line:  "APPROVED <FULLSHA>"
//   Both release-flow.js --cut and CI's release-gate.yml verify this exact path and
//   format. The file MUST be committed to the tag's history.
//
// VERDICT SIGNING (optional, opt-in — see scripts/verdict-keygen.js):
//   Set CW_RELEASE_VERDICT_PRIVKEY (a path or inline PEM) and this script signs
//   the verdict file's exact bytes, writing a sidecar
//   .cw-release/review-<FULLSHA>.verdict.sig (base64 ed25519). Once
//   .cw-release/verdict-signing.pub is committed to the repo, release-gate.yml,
//   npm-publish.yml, and block-unapproved-tag.sh all start REQUIRING a valid
//   signature in addition to the APPROVED text check — closing the gap where
//   anyone with shell access could hand-write a passing verdict file. Until
//   that public key is committed, every check stays exactly as before
//   (grep-only) — this is inert by default, never a silent behavior change.
//
// Test seams (smoke/operator only, never the delegated agent):
//   CW_RELEASE_FLOW_GATE_CMD  overrides the deterministic gate command
//     (default: `bash <thisdir>/release-gate.sh`) so the smoke can exercise the
//     orchestration layer without re-running the full build/test suite.
//   CW_RELEASE_FLOW_GH_CMD    overrides the `gh` binary (single executable token,
//     spawned shell:false) so the smoke can stub GitHub Release calls offline.
//
// Zero dependency for the gated flow: node + git only. The GitHub Release step
// additionally uses `gh` WHEN PRESENT; it lives ONLY in the human --cut --push /
// --release paths (never a gate/CI path) and SKIPS — never fails the cut — when gh
// is absent. A Release is distribution upside layered on the already-pushed tag and
// the provenance-attested npm publish, not a correctness gate.

const fs = require("node:fs");
const path = require("node:path");
const https = require("node:https");
const http = require("node:http");
const crypto = require("node:crypto");
const { spawnSync } = require("node:child_process");

const scriptsDir = __dirname;
const pluginRoot = path.resolve(scriptsDir, "..");

// ---- args ------------------------------------------------------------------
const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);
const val = (f) => {
  const i = argv.indexOf(f);
  return i >= 0 ? argv[i + 1] : undefined;
};
const MODE_CUT = has("--cut");
const MODE_RELEASE = has("--release");
const DRY_RUN = has("--dry-run");
const PUSH = has("--push");
const NO_RELEASE = has("--no-release");
const SOFT = has("--soft");
const cutVersion = val("--version");
const prevTagArg = val("--prev-tag");

function die(msg, extra) {
  process.stderr.write(`release-flow: ${msg}\n`);
  if (extra) process.stderr.write(`${extra}\n`);
  process.exit(1);
}
function say(msg) {
  process.stdout.write(`${msg}\n`);
}
function git(args, opts = {}) {
  const r = spawnSync("git", args, { cwd: repoRoot, encoding: "utf8", ...opts });
  return { code: r.status, out: (r.stdout || "").trim(), err: (r.stderr || "").trim() };
}

// ---- repo + revision context ----------------------------------------------
const top = spawnSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8" });
if (top.status !== 0) die("not inside a git work tree");
const repoRoot = top.stdout.trim();

const HEAD = git(["rev-parse", "HEAD"]).out;
// Previous tag, excluding any tag that already points at HEAD (so this works
// whether run before tagging or re-run on a freshly tagged commit — same fix
// as release-gate.sh).
function resolvePrevTag() {
  if (prevTagArg) return prevTagArg;
  const headTags = git(["tag", "--points-at", "HEAD"]).out.split("\n").filter(Boolean);
  let prev = git(["describe", "--tags", "--abbrev=0"]).out;
  if (prev && headTags.includes(prev)) prev = git(["describe", "--tags", "--abbrev=0", "HEAD^"]).out;
  return prev || "";
}
const PREV_TAG = resolvePrevTag();

// ---- 1. deterministic gate -------------------------------------------------
function runGate() {
  const override = (process.env.CW_RELEASE_FLOW_GATE_CMD || "").trim();
  say("[1/3] deterministic gate");
  let r;
  if (override) {
    // Test/override seam — run via the shell intentionally; this path is for
    // the smoke and operator overrides only, never the delegated agent.
    r = spawnSync(override, { cwd: repoRoot, encoding: "utf8", shell: true, stdio: "inherit" });
  } else {
    r = spawnSync("bash", [path.join(scriptsDir, "release-gate.sh")], {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: "inherit"
    });
  }
  if (r.status !== 0) die("deterministic gate FAILED — fix findings in normal cycles, do not retry the release here.");
}

// ---- 1b. vendor liveness preflight (cut only) ------------------------------
// CW promises claude/codex/gemini/deepseek all work; this proves it before a cut.
// LIVE: spends real tokens on each vendor, so it runs on --cut (release machine
// has the keys), not on --check. HARD-BLOCK: any vendor not green stops the cut.
// Escape hatch CW_SKIP_VENDOR_PREFLIGHT=1 (emergencies/offline). Test seam
// CW_RELEASE_FLOW_PREFLIGHT_CMD overrides the command (smoke stubs it).
function runVendorPreflight() {
  if (!MODE_CUT) {
    say("[1b/3] vendor preflight — skipped (check mode; live vendor calls run on --cut)");
    return;
  }
  if (process.env.CW_SKIP_VENDOR_PREFLIGHT === "1") {
    say("[1b/3] vendor preflight — SKIPPED via CW_SKIP_VENDOR_PREFLIGHT=1 (operator override)");
    return;
  }
  const vendors = (process.env.CW_PREFLIGHT_VENDORS || "claude,codex,gemini,deepseek").trim();
  const override = (process.env.CW_RELEASE_FLOW_PREFLIGHT_CMD || "").trim();
  say(`[1b/3] vendor preflight — live liveness check: ${vendors}`);
  let r;
  if (override) {
    // Test/override seam — shell:true, smoke/operator only, never the delegated agent.
    r = spawnSync(override, { cwd: repoRoot, encoding: "utf8", shell: true, stdio: "inherit" });
  } else {
    r = spawnSync(process.execPath, [path.join(scriptsDir, "vendor-preflight.js"), "--vendors", vendors], {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: "inherit"
    });
  }
  if (r.status !== 0) {
    die("vendor preflight FAILED — a promised vendor is not live (missing CLI/key or broken). Users must not be limited to one vendor; fix before cutting, or set CW_SKIP_VENDOR_PREFLIGHT=1 to override.");
  }
}

// ---- 2. independent reviewer, delegated to the configured agent -------------
// Default reviewer deadline. The zero-trust reviewer re-runs release-gate.sh,
// whose sequential test suite alone is ~12 min, then reads + reasons over the
// diff — so a 10-min default guaranteed a timeout on a real release. 30 min gives
// headroom; override with CW_AGENT_TIMEOUT_MS (or --agent-timeout-ms).
const REVIEWER_TIMEOUT_MS = 1800000;
function reviewerPromptBody() {
  // Reuse the committed reviewer spec as the prompt; strip YAML frontmatter.
  const specPath = path.join(pluginRoot, "agents", "release-reviewer.md");
  let body = fs.existsSync(specPath) ? fs.readFileSync(specPath, "utf8") : "";
  body = body.replace(/^---[\s\S]*?---\n/, "");
  return body.trim();
}

function buildReviewerInput(resultPath) {
  const action = MODE_CUT ? `tag v${cutVersion || "<next>"}` : "check (no tag)";
  const resultDisplay = path.relative(repoRoot, resultPath);
  return [
    reviewerPromptBody(),
    "",
    "---",
    "## Release candidate context (derive/verify everything yourself)",
    `- HEAD: ${HEAD}`,
    `- Previous tag: ${PREV_TAG || "(none)"}`,
    `- Diff range: ${PREV_TAG ? `${PREV_TAG}..HEAD` : "(no previous tag)"}`,
    `- Proposed action: ${action}`,
    "- Repo root (run git here): .",
    "",
    "## Required output — write ONLY this file, nothing else",
    `Write your verdict to this exact path:`,
    `  ${resultDisplay}`,
    "First line MUST be exactly one of:",
    `  APPROVED ${HEAD}`,
    "  <one concrete sentence: the user-visible capability this ships>",
    "or:",
    "  REJECTED",
    "  <numbered gate failures with file:line references>",
    "",
    "If your host wrapper asks for Markdown, JSON, or a fenced result block, still put",
    "the exact APPROVED/REJECTED verdict line above as a standalone line outside any",
    "prose or code fence. The release tool extracts only strict standalone verdict",
    "lines; prose such as 'Verdict: APPROVED' is not trusted.",
    ""
  ].join("\n");
}

function substitute(arg, map) {
  return arg.replace(/\{\{(\w+)\}\}/g, (m, k) => (k in map ? String(map[k]) : m));
}

/** Extract verdict lines from agent stdout. Returns the verdict text (first line
 *  must be APPROVED <sha> or REJECTED) or null if no valid verdict found.
 *  Also logs failures to stderr so the operator can inspect. */
function extractVerdictFromStdout(stdout, resultPath) {
  const lines = stdout.split(/\r?\n/);
  const approvedLine = lines.find((line) => /^APPROVED\s+\S+/.test(line.trim()));
  if (approvedLine) {
    const idx = lines.indexOf(approvedLine);
    // Include the APPROVED line and any capability line that follows.
    const capLine = (lines[idx + 1] || "").trim();
    const verdict = capLine && !capLine.startsWith("#") && !/^(APPROVED|REJECTED)\s/.test(capLine)
      ? [approvedLine.trim(), capLine].join("\n")
      : approvedLine.trim();
    say(`reviewer verdict captured from stdout → ${resultPath}`);
    return verdict;
  }
  const rejectedLine = lines.find((line) => /^REJECTED/i.test(line.trim()));
  if (rejectedLine) {
    process.stderr.write(`reviewer REJECTED via stdout — full output:\n${stdout.trim()}\n`);
    return rejectedLine.trim();
  }
  // Partial: print the last 20 lines to help the operator diagnose.
  process.stderr.write(`reviewer stdout had no APPROVED/REJECTED line. Last 20 lines:\n${lines.slice(-20).join("\n").trim()}\n`);
  return null;
}

function delegateReview(resultPath, inputPath) {
  // Reuse the canonical agent-config resolver (flags > env > file).
  let resolveAgentConfig;
  try {
    ({ resolveAgentConfig } = require(path.join(pluginRoot, "dist", "shell", "agent-config.js")));
  } catch (e) {
    die("cannot load dist/shell/agent-config.js — run `npm run build` first", String(e));
  }
  const cfg = resolveAgentConfig(
    { "agent-command": val("--agent-command"), "agent-model": val("--agent-model") },
    process.env
  );
  if (cfg.source === "none" || (!cfg.command && !cfg.endpoint)) {
    die(
      "no reviewer agent configured. Set one of:\n" +
      '  CW_AGENT_COMMAND="claude -p {{input}}"   (or codex exec / gemini -p / opencode run)\n' +
      "  CW_AGENT_ENDPOINT=https://...            (HTTP agent, e.g. DeepSeek)\n" +
      "  or pass --agent-command. CW delegates the review; it never runs a model itself."
    );
  }

  const subMap = {
    input: path.relative(repoRoot, inputPath),
    manifest: path.relative(repoRoot, inputPath),
    result: path.relative(repoRoot, resultPath),
    workerDir: ".",
    model: cfg.model || "",
    prompt: fs.readFileSync(inputPath, "utf8")
  };

  if (cfg.command) {
    // cfg.command can arrive as a SINGLE unsplit multi-token string. A
    // builtin:<vendor> template (CW_AGENT_COMMAND=builtin:claude) expands to
    // "node /abs/claude-p-agent.js {{input}} {{result}}" with cfg.args undefined,
    // and a durable agent-config.json command field is read verbatim (no split).
    // Split it on whitespace into binary + inline args — the SAME way the
    // orchestrator does (src/execution-backend/agent.ts resolveAgentInvocation) —
    // so we spawn the real binary, never one literally named
    // "node /abs/... {{input}}" (an instant ENOENT the old code mislabeled as a
    // timeout). An explicit cfg.args array still follows the inline args. A plain
    // CW_AGENT_COMMAND="claude -p {{input}}" is already pre-split by
    // resolveAgentConfig, so this leaves it unchanged (no inline args).
    const parts = cfg.command.split(/\s+/).filter(Boolean);
    const bin = parts[0];
    const argTemplate = [...parts.slice(1), ...(cfg.args || [])];
    const args = argTemplate.map((a) => substitute(a, subMap));
    say(`[2/3] reviewer — delegating to: ${bin} ${argTemplate.join(" ")} (model: ${cfg.model || "unreported"})`);
    // RED LINE: argv-style, shell:false. The agent runs the model in its own
    // process and inherits its own credentials; CW holds none.
    // Capture stdout so agents that print verdicts (rather than writing the
    // result file) are supported. Agents that DO write the file still work:
    // the file takes precedence. stderr goes to the terminal for live output.
    const r = spawnSync(bin, args, {
      cwd: repoRoot,
      // CW_RELEASE_REVIEW=1 is a vendor-agnostic signal that THIS spawn is a
      // release verdict, not a fast worker turn. Wrappers that can re-run the gate
      // (e.g. codex-agent.js) read it to raise reasoning effort and open an
      // exec-capable sandbox — a read-only/low-effort reviewer can't execute the
      // gate it judges and degrades to fabricated verdicts. Preflight liveness
      // probes never set it, so they stay fast and read-only.
      env: { ...process.env, CW_RELEASE_REVIEW: "1" },
      encoding: "utf8",
      timeout: cfg.timeoutMs || REVIEWER_TIMEOUT_MS,
      shell: false,
      stdio: ["ignore", "pipe", "inherit"],
      maxBuffer: 32 * 1024 * 1024
    });
    // A spawn that never started (ENOENT for a missing binary, ETIMEDOUT on the
    // deadline) sets r.error — surface its real message instead of the old
    // catch-all "(timeout/no-exit)" that hid the builtin: ENOENT for so long.
    if (r.error) die(`reviewer agent could not be spawned (${bin}): ${r.error.message} — no verdict trusted.`);
    if (r.status !== 0) die(`reviewer agent exited ${r.status === null ? "(timeout/no-exit)" : r.status} — no verdict trusted.`);
    // If the agent already wrote the verdict file (backward compat), use it.
    // Otherwise extract the verdict from stdout (headless agent path).
    if (fs.existsSync(resultPath)) return;
    const stdout = String(r.stdout || "").trim();
    if (stdout) {
      const verdictLines = extractVerdictFromStdout(stdout, resultPath);
      if (verdictLines) {
        fs.writeFileSync(resultPath, `${verdictLines}\n`);
        return;
      }
    }
    die("reviewer agent produced no verdict — stdout had no APPROVED <sha> or REJECTED line, and no verdict file was written. Ensure the agent writes the verdict to {{result}} or prints the verdict lines to stdout.");
  }

  // Endpoint mode (e.g. DeepSeek HTTP): POST the prompt, write the response as
  // the verdict. The remote agent cannot write our local file, so we persist
  // its returned text ourselves.
  say(`[2/3] reviewer — POSTing to endpoint ${cfg.endpoint} (model: ${cfg.model || "unreported"})`);
  const body = JSON.stringify({ prompt: subMap.prompt, model: cfg.model, sha: HEAD });
  const lib = cfg.endpoint.startsWith("https:") ? https : http;
  const text = postSync(lib, cfg.endpoint, body, cfg.timeoutMs || REVIEWER_TIMEOUT_MS);
  if (text === null) die("reviewer endpoint call failed — no verdict trusted.");
  fs.writeFileSync(resultPath, text.endsWith("\n") ? text : `${text}\n`);
}

// Minimal synchronous-ish POST using a child node process would overcomplicate;
// use a blocking wait via Atomics on a SharedArrayBuffer-free approach: do a
// simple promise + deasync-free busy loop is not available, so use execFileSync
// with curl ONLY if present; otherwise instruct the operator to use command mode.
function postSync(lib, endpoint, body, timeoutMs) {
  const curl = spawnSync("curl", [
    "-sS", "--max-time", String(Math.ceil(timeoutMs / 1000)),
    "-X", "POST", "-H", "Content-Type: application/json",
    "--data-binary", body, endpoint
  ], { encoding: "utf8" });
  if (curl.error || curl.status !== 0) {
    process.stderr.write(curl.stderr || String(curl.error || "curl failed") + "\n");
    return null;
  }
  return curl.stdout || "";
}

function verifyVerdict(resultPath) {
  say("[3/3] verify verdict");
  if (!fs.existsSync(resultPath)) die(`no verdict written to ${path.relative(repoRoot, resultPath)} — fail closed.`);
  const text = fs.readFileSync(resultPath, "utf8");
  const lines = text.split(/\r?\n/);
  const firstLine = lines[0] || "";
  if (firstLine !== `APPROVED ${HEAD}`) {
    if (firstLine.toUpperCase() !== "REJECTED") {
      const normalized = extractVerdictFromStdout(text, resultPath);
      if (normalized && normalized.split(/\r?\n/)[0] === `APPROVED ${HEAD}`) {
        fs.writeFileSync(resultPath, `${normalized}\n`);
        const normalizedLines = normalized.split(/\r?\n/);
        return (normalizedLines[1] || "").trim();
      }
    }
    die(`verdict first line must be exactly "APPROVED ${HEAD}" — release blocked.`, text.trim());
  }
  const cap = (lines[1] || "").trim();
  return cap;
}

// ---- verdict signing (optional, opt-in — see the header comment) -----------
function resolveVerdictPrivateKey(value) {
  const trimmed = String(value).trim();
  if (trimmed.includes("BEGIN") && trimmed.includes("KEY")) return trimmed;
  if (fs.existsSync(trimmed)) return fs.readFileSync(trimmed, "utf8");
  die(`CW_RELEASE_VERDICT_PRIVKEY does not point to a readable key file or inline PEM: ${trimmed}`);
}

/** Called only after verifyVerdict() has confirmed resultPath's bytes are a
 *  genuine "APPROVED <HEAD>" verdict. A no-op unless CW_RELEASE_VERDICT_PRIVKEY
 *  is set. When it IS set, a signing failure fails closed (die()) rather than
 *  silently emitting an unsigned verdict — an operator who deliberately
 *  configured a signing key should never end up with the same on-disk state
 *  as one who didn't. */
function signVerdictIfConfigured(resultPath) {
  const raw = process.env.CW_RELEASE_VERDICT_PRIVKEY;
  if (!raw || !raw.trim()) return;
  const pem = resolveVerdictPrivateKey(raw);
  const sigPath = `${resultPath}.sig`;
  try {
    const key = crypto.createPrivateKey(pem);
    // crypto.sign(null, ...) does NOT throw for an RSA or EC key — it silently
    // signs with that algorithm's own default digest, producing a
    // syntactically valid signature that can never verify against the
    // committed ed25519 public key. Catching that here, at signing time,
    // means a misconfigured key dies closed locally instead of only being
    // caught later by CI (or not at all, if the repo hasn't committed
    // verdict-signing.pub yet).
    if (key.asymmetricKeyType !== "ed25519") {
      die(`CW_RELEASE_VERDICT_PRIVKEY is a ${key.asymmetricKeyType || "unknown"} key, not ed25519 — generate one with scripts/verdict-keygen.js`);
    }
    const message = fs.readFileSync(resultPath);
    const signature = crypto.sign(null, message, key).toString("base64");
    fs.writeFileSync(sigPath, `${signature}\n`);
  } catch (error) {
    die(`failed to sign the verdict with CW_RELEASE_VERDICT_PRIVKEY: ${error.message}`);
  }
  say(`verdict signed → ${path.relative(repoRoot, sigPath)}`);
}

// ---- GitHub Release (optional, presentation/distribution) ------------------
// NOT a correctness gate: the load-bearing artifacts (the tag + the
// provenance-attested npm publish) already exist when this runs. So `gh` is NOT
// part of the node/git portability floor — it runs ONLY in the human --cut --push
// / --release paths (never a gate/CI path), and an absent/erroring gh SKIPS with a
// stderr note rather than failing the cut. Test seam: CW_RELEASE_FLOW_GH_CMD swaps
// the `gh` binary for a stub (single executable token; always spawned shell:false).
const GH_BIN = (process.env.CW_RELEASE_FLOW_GH_CMD || "gh").trim();

function gh(args, opts = {}) {
  // shell:false is AFTER the spread so no caller can override the red line.
  return spawnSync(GH_BIN, args, { cwd: repoRoot, encoding: "utf8", ...opts, shell: false });
}

// gh present AND authenticated. Absent/unauth → false (caller skips, not fails).
function ghReady() {
  const v = gh(["--version"]);
  if (v.error || v.status !== 0) return false;
  const auth = gh(["auth", "status"]);
  return !auth.error && auth.status === 0;
}

function repoSlug() {
  const url = git(["remote", "get-url", "origin"]).out;
  const m = url.match(/github\.com[:/]+([^/]+?)\/(.+?)(?:\.git)?$/);
  return m ? { owner: m[1], repo: m[2] } : null;
}

// The previous release tag relative to a SPECIFIC tag (not HEAD) — for the
// compare link in the notes.
function prevTagOf(version) {
  return git(["describe", "--tags", "--abbrev=0", `v${version}^`]).out || "";
}

// Full regex escape (same shape as parity-check.js's helper — scripts stay
// zero-dependency single files, so it is copied, not required). The version
// is SEMVER-validated on every path that reaches here, but escaping every
// metacharacter costs nothing and keeps the RegExp construction safe on its
// own terms.
function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Extract the `## <version>` section body from the CHANGELOG AS SHIPPED AT THE
// TAG (git show), so the notes reflect what that tag actually carried.
function changelogSection(version) {
  const show = git(["show", `v${version}:CHANGELOG.md`]);
  if (show.code !== 0 || !show.out) return "";
  const lines = show.out.split(/\r?\n/);
  const esc = escapeRegExp(version);
  const startRe = new RegExp(`^## \\[?${esc}\\b`);
  let start = -1;
  for (let i = 0; i < lines.length; i++) if (startRe.test(lines[i])) { start = i; break; }
  if (start < 0) return "";
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) if (/^## /.test(lines[i])) { end = i; break; }
  return lines.slice(start + 1, end).join("\n").trim();
}

// Resolve the reviewed content commit + capability from the COMMITTED verdict at
// the tag, mirroring release-gate.yml's HEAD-or-HEAD~1 tolerance: the verdict is
// named for the reviewed content commit, which is the tag commit or its parent.
function verdictForTag(version) {
  const tagCommit = git(["rev-list", "-n1", `v${version}`]).out;
  const parent = git(["rev-parse", `v${version}^`]).out;
  for (const sha of [tagCommit, parent].filter(Boolean)) {
    const rel = `.cw-release/review-${sha}.verdict`;
    const show = git(["show", `v${version}:${rel}`]);
    if (show.code === 0 && /^APPROVED /.test(show.out)) {
      const cap = (show.out.split(/\r?\n/)[1] || "").trim();
      return { contentSha: sha, capability: cap, verdictRel: rel };
    }
  }
  return { contentSha: "", capability: "", verdictRel: "" };
}

// Pure: assemble the release-notes markdown from already-gathered inputs. No I/O,
// so the smoke can assert the rendered notes (capability headline, CHANGELOG body,
// provenance footer links) without touching git or the network.
function buildReleaseNotes({ version, capability, changelog, slug, contentSha, verdictRel, prevTag }) {
  const base = slug ? `https://github.com/${slug.owner}/${slug.repo}` : "";
  const out = [];
  if (capability) out.push(`> ${capability}`, "");
  if (changelog) out.push(changelog, "");
  out.push("---", "", "### Provenance & audit", "");
  if (base && contentSha) out.push(`- **Reviewed commit:** [\`${contentSha.slice(0, 12)}\`](${base}/commit/${contentSha})`);
  if (base && verdictRel) out.push(`- **Independent reviewer verdict (committed):** [\`${verdictRel}\`](${base}/blob/v${version}/${verdictRel})`);
  if (base && prevTag) out.push(`- **Full diff:** [\`${prevTag}...v${version}\`](${base}/compare/${prevTag}...v${version})`);
  out.push(`- **npm (provenance-attested):** [\`cool-workflow@${version}\`](https://www.npmjs.com/package/cool-workflow/v/${version})`);
  // The gated-flow claim is made ONLY when a committed reviewer verdict actually
  // backs it — otherwise the notes would assert a review that is not there
  // (a false-green CW exists to prevent). Backfilled/ungated tags get an honest
  // caveat instead.
  if (verdictRel) {
    out.push("", "_Released through the gated flow: deterministic gate → independent release-reviewer (verdict above) → provenance-attested npm publish._");
  } else {
    out.push("", "_Backfilled Release: no committed reviewer verdict was found at this tag, so these notes make no gated-review claim — integrity rests on the provenance-attested npm publish above._");
  }
  return `${out.join("\n").trim()}\n`;
}

// Create-or-skip the GitHub Release for an already-pushed tag. `required` (the
// standalone --release mode) → an absent/failed gh is an ERROR; otherwise (the
// cut finishing step) → skip-with-note and DO NOT fail the cut.
function releaseGitHub(version, { required = false } = {}) {
  if (!/^\d+\.\d+\.\d+$/.test(version || "")) die("release requires a x.y.z version");
  const tag = `v${version}`;
  if (git(["rev-parse", "-q", "--verify", `refs/tags/${tag}`]).code !== 0) {
    const msg = `tag ${tag} not found locally — push the tag before creating its Release.`;
    if (required) die(msg);
    process.stderr.write(`release-flow: note: ${msg} skipping Release.\n`);
    return false;
  }
  if (!ghReady()) {
    const msg = `gh CLI not available/authenticated — cannot create GitHub Release ${tag}. Create it later: gh release create ${tag} --notes-file <notes> --verify-tag`;
    if (required) die(msg);
    process.stderr.write(`release-flow: note: ${msg}\n`);
    return false;
  }
  if (gh(["release", "view", tag]).status === 0) {
    say(`GitHub Release ${tag} already exists — skipping (idempotent).`);
    return true;
  }
  const { contentSha, capability, verdictRel } = verdictForTag(version);
  if (!verdictRel) {
    process.stderr.write(`release-flow: note: no committed APPROVED verdict found at ${tag} — the Release notes will make NO gated-review claim (backfilling an ungated tag).\n`);
  }
  const notes = buildReleaseNotes({
    version,
    capability,
    changelog: changelogSection(version),
    slug: repoSlug(),
    contentSha,
    verdictRel,
    prevTag: prevTagOf(version)
  });
  const notesPath = path.join(repoRoot, ".cw-release", `release-notes-${version}.md`);
  fs.mkdirSync(path.dirname(notesPath), { recursive: true });
  fs.writeFileSync(notesPath, notes);
  if (DRY_RUN) { say(`[dry-run] would: gh release create ${tag} --notes-file ${notesPath} --verify-tag`); return true; }
  const r = gh(["release", "create", tag, "--title", tag, "--notes-file", notesPath, "--verify-tag"], { stdio: "inherit" });
  if (r.status !== 0) {
    const msg = `gh release create failed for ${tag} — notes saved at ${notesPath}; the tag and npm publish are unaffected.`;
    if (required) die(msg);
    process.stderr.write(`release-flow: note: ${msg}\n`);
    return false;
  }
  say(`created GitHub Release ${tag}.`);
  return true;
}

// ---- 2b. cut preflight (fail fast, BEFORE any paid step) --------------------
// Every check here answers one question: "will this cut die AFTER the gate,
// the live vendor preflight, and the reviewer have already run?" Each check
// was a real post-reviewer failure in the v0.2.3 cut (2026-07-10) — a missing
// --version, an unsigned verdict the CI gate then rejected, a left-over local
// tag, and a two-hop recovery that broke the HEAD~1 topology rule. All of
// them are answerable in under a second, so answer them FIRST.
//
// Fixture safety: each check is gated on the thing it checks being present
// (a committed signing pubkey, a CHANGELOG.md, an `origin` remote), so the
// smoke fixtures — bare repos with none of those — pass through untouched.
function preflightCut() {
  say("[0/3] cut preflight");
  // (a) version — cheap and load-bearing for every later step. Checking it
  // here (not only inside cut()) is what stops a full gate+reviewer run from
  // being thrown away over a missing flag.
  if (!cutVersion || !/^\d+\.\d+\.\d+$/.test(cutVersion)) die("--cut requires --version x.y.z");

  // (b) signing — once .cw-release/verdict-signing.pub is committed, CI's
  // release-gate REQUIRES a valid signature; a cut without the private key
  // configured would push an unsigned verdict that fails only in CI. Fail
  // closed here instead, and also prove the configured key IS the committed
  // key (a wrong key signs "successfully" and still fails in CI).
  const pubPath = path.join(repoRoot, ".cw-release", "verdict-signing.pub");
  if (fs.existsSync(pubPath)) {
    const raw = process.env.CW_RELEASE_VERDICT_PRIVKEY;
    if (!raw || !raw.trim()) {
      die(
        "verdict-signing.pub is committed, so CI requires a SIGNED verdict — set the private key first",
        'fix:  export CW_RELEASE_VERDICT_PRIVKEY=~/.cw-keys/verdict-signing.key'
      );
    }
    const pem = resolveVerdictPrivateKey(raw);
    let key;
    try {
      key = crypto.createPrivateKey(pem);
    } catch (error) {
      die(`CW_RELEASE_VERDICT_PRIVKEY is not a readable private key: ${error.message}`);
    }
    if (key.asymmetricKeyType !== "ed25519") {
      die(`CW_RELEASE_VERDICT_PRIVKEY is a ${key.asymmetricKeyType || "unknown"} key, not ed25519 — generate one with scripts/verdict-keygen.js`);
    }
    const derivedPub = crypto.createPublicKey(key).export({ type: "spki", format: "pem" }).toString().trim();
    const committedPub = fs.readFileSync(pubPath, "utf8").trim();
    if (derivedPub !== committedPub) {
      die("CW_RELEASE_VERDICT_PRIVKEY does not match the committed .cw-release/verdict-signing.pub — wrong key; CI would reject its signature");
    }
  }

  // (c) tag must not exist yet — a stale local tag makes cut() die at the very
  // last step ("tag 'vX.Y.Z' already exists") after everything else has run.
  if (git(["tag", "-l", `v${cutVersion}`]).out) {
    die(`tag v${cutVersion} already exists locally — delete it first (git tag -d v${cutVersion}) or pick the next version`);
  }

  // (d) CHANGELOG must already carry the release section — release notes get
  // pasted verbatim into the GitHub Release, and bump:version's content gate
  // would only catch this inside cut(), after the reviewer.
  const changelogPath = path.join(repoRoot, "CHANGELOG.md");
  if (fs.existsSync(changelogPath) && !fs.readFileSync(changelogPath, "utf8").includes(`## ${cutVersion}`)) {
    die(`CHANGELOG.md has no "## ${cutVersion}" section — write the release notes first`);
  }

  // (e) clean tree (tracked files only — cut()'s `git add -u` can never sweep
  // an untracked stray in, so untracked files are not a cut hazard).
  const dirty = git(["status", "--porcelain", "-uno"]).out;
  if (dirty) die("working tree has tracked modifications — commit or stash them before a cut", dirty);

  // (f) network-dependent checks, only when this cut will actually push and
  // only when an `origin` remote exists (smoke fixtures have none):
  if (PUSH && git(["remote"]).out.split("\n").includes("origin")) {
    // remote tag must not exist (someone/some run already published this version)
    const remoteTag = git(["ls-remote", "origin", `refs/tags/v${cutVersion}`]);
    if (remoteTag.code === 0 && remoteTag.out) {
      die(`tag v${cutVersion} already exists on origin — this version is already published; pick the next version`);
    }
    // HEAD must be the current origin/main tip — cutting a stale HEAD publishes
    // old code (nearly happened on the v0.2.2 cut).
    if (git(["fetch", "origin", "main", "--quiet"]).code !== 0) {
      die("git fetch origin main failed — a --push cut needs the network anyway; fix connectivity first");
    }
    const mainTip = git(["rev-parse", "origin/main"]).out;
    if (mainTip !== HEAD && !has("--allow-stale-head")) {
      die(
        `HEAD (${HEAD.slice(0, 12)}) is not the origin/main tip (${mainTip.slice(0, 12)}) — a cut must release exactly what main has`,
        "fix:  git fetch origin main && git checkout -B <branch> origin/main   (or pass --allow-stale-head if this is deliberate)"
      );
    }
  }
  say("cut preflight OK");
}

// ---- 3. optional cut (bump + commit verdict + tag + push) ------------------
function cut(resultPath, capability) {
  if (!cutVersion || !/^\d+\.\d+\.\d+$/.test(cutVersion)) die("--cut requires --version x.y.z");
  if (DRY_RUN) { say(`[dry-run] would: bump:version ${cutVersion}, commit verdict, tag v${cutVersion}${PUSH ? `, push refs/tags/v${cutVersion} (tag only, no branch)` : ""}`); return; }
  const bump = spawnSync("npm", ["run", "bump:version", "--", cutVersion], { cwd: pluginRoot, encoding: "utf8", stdio: "inherit" });
  if (bump.status !== 0) die("bump:version failed");
  // Regenerate the gated project index after the version bump (PR #87 gate).
  // Fail closed: a failed regen must not bake a stale index into the immutable tag.
  const sync = spawnSync("npm", ["run", "sync:project-index", "--", "--repo-only"], { cwd: pluginRoot, encoding: "utf8", stdio: "inherit" });
  if (sync.status !== 0) die("sync:project-index failed — refusing to cut with a stale project index");
  // Stage ONLY tracked-file modifications (the bump surfaces, project-index, dist)
  // plus the ONE intended new file: the reviewer verdict. NEVER `git add -A` — an
  // untracked stray (e.g. the reviewer's narration transcript, which carries the
  // operator's local home path) must never ride into the immutable tag commit
  // (that tripped pii-redaction-smoke and red-failed release-gate for v0.1.96).
  // `git add -u` touches tracked files only, so no untracked file can be swept in;
  // the verdict (and its .sig sidecar, when verdict signing is configured) are
  // the only new paths the cut is allowed to add.
  git(["add", "-u"]);
  git(["add", "--", path.relative(repoRoot, resultPath)]);
  const sigPath = `${resultPath}.sig`;
  if (fs.existsSync(sigPath)) git(["add", "--", path.relative(repoRoot, sigPath)]);
  const commit = git(["commit", "-m", `chore(release): record APPROVED reviewer verdict for v${cutVersion}`]);
  if (commit.code !== 0) die("verdict commit failed", commit.err);
  const tag = git(["tag", "-a", `v${cutVersion}`, "-m", `v${cutVersion}: ${capability || "release"}`]);
  if (tag.code !== 0) die("git tag failed", tag.err);
  if (PUSH) {
    // Push ONLY the tag. The verdict commit is a one-hop leaf on the reviewed
    // main-tip commit, reachable through the tag alone — it does not need to
    // be on any branch. Pushing HEAD here used to (a) hit main's branch
    // protection (enforce_admins blocks even the owner's direct push) or
    // (b) mint a stray remote branch named after whatever branch the cut ran
    // from. Tags are not protected in this repo, and CI's release-gate checks
    // the TAG's own history (verdict at HEAD or HEAD~1), so the tag alone is
    // the complete release artifact — proven live by the v0.2.3 cut.
    const push = git(["push", "origin", `refs/tags/v${cutVersion}`]);
    if (push.code !== 0) die("tag push failed (nothing was pushed)", push.err);
  }
  say(`tagged v${cutVersion}${PUSH ? " and pushed" : " (local only; push when ready)"}`);
  // Finishing step: create the GitHub Release for the just-pushed tag. Only when
  // pushed (the remote tag must exist) and not opted out; never fails the cut.
  if (PUSH && !NO_RELEASE) releaseGitHub(cutVersion, { required: false });
}

// ---- main ------------------------------------------------------------------
function main() {
  if (!HEAD) die("could not resolve HEAD");

  // Standalone backfill: create-or-skip the GitHub Release for an already-pushed
  // tag. No gate, no review, no mutation of tracked files — just GitHub.
  if (MODE_RELEASE) {
    const version = cutVersion;
    if (!version || !/^\d+\.\d+\.\d+$/.test(version)) die("--release requires --version x.y.z");
    // Default: fail closed if gh can't create the Release (the operator asked for
    // it directly). --soft downgrades to best-effort (skip-not-fail), the same
    // semantics the --cut --push finishing step uses.
    const created = releaseGitHub(version, { required: !SOFT });
    process.stdout.write(`${JSON.stringify({ ok: true, mode: "release", version, soft: SOFT, created }, null, 2)}\n`);
    return;
  }

  // Fail-fast checks FIRST — nothing below (gate, live vendor calls, the
  // reviewer) runs until every cheap precondition holds. --preflight-only
  // lets an orchestrator (release-oneclick.js) run just this step. Without
  // --cut there is no preflight to run, so answering ok:true would be a
  // green light with zero checks done — refuse instead.
  if (has("--preflight-only") && !MODE_CUT) die("--preflight-only requires --cut (there is no preflight to run in check/release mode)");
  if (MODE_CUT) preflightCut();
  if (has("--preflight-only")) {
    process.stdout.write(`${JSON.stringify({ ok: true, mode: "preflight", version: cutVersion || null }, null, 2)}\n`);
    return;
  }

  const markerDir = path.join(repoRoot, ".cw-release");
  fs.mkdirSync(markerDir, { recursive: true });
  const resultPath = path.join(markerDir, `review-${HEAD}.verdict`);
  const inputPath = path.join(markerDir, `review-input-${HEAD}.md`);

  runGate();
  runVendorPreflight();
  fs.writeFileSync(inputPath, buildReviewerInput(resultPath));
  delegateReview(resultPath, inputPath);
  const capability = verifyVerdict(resultPath);
  signVerdictIfConfigured(resultPath);

  if (MODE_CUT) cut(resultPath, capability);

  process.stdout.write(`${JSON.stringify({
    ok: true,
    mode: MODE_CUT ? "cut" : "check",
    head: HEAD,
    prevTag: PREV_TAG || null,
    verdict: "APPROVED",
    capability,
    tagged: MODE_CUT && !DRY_RUN ? `v${cutVersion}` : null
  }, null, 2)}\n`);
}

main();
