#!/usr/bin/env node
"use strict";

// sync-readme — keep the npm package README in lockstep with the GitHub README.
//
// The repo-root README.md is the SINGLE SOURCE OF TRUTH. This generates the npm
// page (plugins/cool-workflow/README.md) from it, changing ONLY what npm needs to
// render: relative URLs become absolute, because npm cannot resolve a repo's
// relative `docs/assets/...` image paths or `](LICENSE)` links the way GitHub can.
//
//   <img src="docs/assets/x.svg">  ->  raw.githubusercontent.com/<owner>/<repo>/main/docs/assets/x.svg
//   ](LICENSE) / ](plugins/...)     ->  github.com/<owner>/<repo>/blob/main/...
//
// The text content is otherwise identical, so the two pages can never drift.
//
// --check : regenerate in memory, compare to the committed npm README, write
//           nothing, exit non-zero on drift (the release/CI gate). Mirrors
//           sync-project-index.js. Fork-safe: the owner/repo in the absolute URLs
//           is normalized out of the compare, so a fork clone never false-REDs.

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

const pluginRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(pluginRoot, "..", "..");
const sourceReadme = path.join(repoRoot, "README.md");
// CW_README_PATH overrides the npm README that --check compares against (used by
// the smoke to point --check at a throwaway drifted fixture). Default: the real one.
const targetReadme = process.env.CW_README_PATH
  ? path.resolve(process.env.CW_README_PATH)
  : path.join(pluginRoot, "README.md");

const repoUrl = normalizeGitRemote(git(["config", "--get", "remote.origin.url"]).trim())
  || "https://github.com/coo1white/cool-workflow";
const ownerRepo = repoUrl.replace(/^https:\/\/github\.com\//, "");
const RAW_BASE = `https://raw.githubusercontent.com/${ownerRepo}/main`;
const BLOB_BASE = `${repoUrl}/blob/main`;

const MARKER =
  "<!-- AUTO-GENERATED from /README.md by scripts/sync-readme.js — edit the root README, " +
  "then run `npm run sync:readme`. DO NOT edit this file directly. -->";

const CHECK = process.argv.includes("--check");

function render() {
  if (!fs.existsSync(sourceReadme)) {
    process.stderr.write(`sync-readme FAILED: source ${path.relative(repoRoot, sourceReadme)} does not exist.\n`);
    process.exit(1);
  }
  const source = fs.readFileSync(sourceReadme, "utf8");
  // NOTE: a relative path must be free of a literal "(", ")", or '"' — the [^)]+ / [^"]+
  // captures below stop at those. The repo README has none; readme:check catches any drift.
  const absolutized = source
    // HTML image sources: <img src="docs/assets/x.svg"> -> raw URL (skip already-absolute / anchors)
    .replace(/\bsrc="(?!https?:|#|data:)([^"]+)"/g, (_m, rel) => `src="${RAW_BASE}/${rel}"`)
    // Markdown links: ](LICENSE) / ](plugins/...) -> blob URL (skip absolute / in-page anchors / mailto)
    .replace(/\]\((?!https?:|#|mailto:)([^)]+)\)/g, (_m, rel) => `](${BLOB_BASE}/${rel})`);
  return `${MARKER}\n${absolutized}`;
}

function normalizeForCompare(text) {
  // Strip the owner/repo from the generated absolute URLs so a fork (whose git
  // remote differs) does not false-RED against the canonical committed README.
  // The CONTENT is what this gate guards; the owner/repo is environment-derived.
  return text
    .replace(/\r\n/g, "\n")
    .replace(/https:\/\/raw\.githubusercontent\.com\/[^/]+\/[^/]+\/main/g, "<RAW>")
    .replace(/https:\/\/github\.com\/[^/]+\/[^/]+\/blob\/main/g, "<BLOB>");
}

function main() {
  const rendered = render();
  const rel = path.relative(repoRoot, targetReadme);

  if (CHECK) {
    if (!fs.existsSync(targetReadme)) {
      process.stderr.write(`readme check FAILED: ${rel} does not exist.\nRun: (cd plugins/cool-workflow && npm run sync:readme)\n`);
      process.exit(1);
    }
    const committed = normalizeForCompare(fs.readFileSync(targetReadme, "utf8"));
    const fresh = normalizeForCompare(rendered);
    if (committed === fresh) {
      process.stdout.write(`${JSON.stringify({ ok: true, check: true, source: "README.md", doc: rel }, null, 2)}\n`);
      return;
    }
    const a = committed.split("\n");
    const b = fresh.split("\n");
    let i = 0;
    while (i < a.length && i < b.length && a[i] === b[i]) i++;
    process.stderr.write(
      `readme check FAILED: ${rel} is stale (does not match the GitHub README.md).\n` +
      `First difference at line ${i + 1}:\n` +
      `  committed: ${JSON.stringify(a[i] ?? "<missing>")}\n` +
      `  expected:  ${JSON.stringify(b[i] ?? "<missing>")}\n` +
      `Regenerate with: (cd plugins/cool-workflow && npm run sync:readme)\n`
    );
    process.exit(1);
  }

  fs.writeFileSync(targetReadme, rendered, "utf8");
  process.stdout.write(`${JSON.stringify({
    ok: true,
    source: "README.md",
    output: rel,
    repoUrl
  }, null, 2)}\n`);
}

function git(args) {
  const result = spawnSync("git", args, { cwd: repoRoot, encoding: "utf8" });
  return result.status === 0 ? result.stdout : "";
}

function normalizeGitRemote(remote) {
  if (!remote) return "";
  if (remote.endsWith(".git")) remote = remote.slice(0, -4);
  const sshMatch = remote.match(/^git@github\.com:(.+)$/);
  if (sshMatch) return `https://github.com/${sshMatch[1]}`;
  return remote;
}

main();
