export const CURRENT_COOL_WORKFLOW_VERSION = "0.1.84";
export const WORKFLOW_APP_SCHEMA_VERSION = 1;
export const CURRENT_RUN_STATE_SCHEMA_VERSION = 1;
export const LEGACY_RUN_STATE_SCHEMA_VERSION = 0;
export const MIN_SUPPORTED_RUN_STATE_SCHEMA_VERSION = 0;
