const FAST_MODEL = modelHint("CW_ARCHITECTURE_REVIEW_FAST_MODEL");
const STRONG_MODEL = modelHint("CW_ARCHITECTURE_REVIEW_STRONG_MODEL");

module.exports = ({ workflow, phase, parallel, agent, artifact, input }) => {
  const inputs = [
    input("repo", {
      type: "path",
      required: true,
      description: "Repository path to inspect."
    }),
    input("question", {
      type: "string",
      required: true,
      description: "Architecture question or decision to review."
    }),
    input("invariant", {
      type: "string",
      repeated: true,
      description: "Invariant that must remain true."
    }),
    input("focus", {
      type: "string",
      description: "Optional subsystem, risk area, or file path to emphasize.",
      default: "the highest-risk runtime and operator paths"
    }),
    input("sourceContext", {
      type: "path",
      description: "Optional JSONL source context file generated by scripts/source-context.js export.",
      default: ""
    }),
    input("sourceContextDigest", {
      type: "string",
      description: "Optional digest or cache key for the supplied source context.",
      default: ""
    })
  ];

  return workflow({
    id: "architecture-review-fast",
    title: "Architecture Review Fast",
    summary: "Run a shorter architecture review with parallel map and assess phases for faster first results.",
    limits: {
      maxAgents: 12,
      maxConcurrentAgents: 4
    },
    inputs,
    sandboxProfiles: ["readonly"],
    metadata: {
      mode: "fast",
      fullReviewApp: "architecture-review"
    },
    phases: [
      parallel("Map", [
        agent(
          "map:runtime-surface",
          [
            "Fast-map the runtime architecture in {{repo}} for {{question}}.",
            contextInstruction(),
            "Focus: {{focus}}. Invariants: {{invariant}}.",
            "Return the primary entrypoints, state stores, execution paths, and the exact files or commands inspected."
          ].join(" "),
          fastOptions("Runtime surface mapper", { resultCache: sourceContextResultCache() })
        ),
        agent(
          "map:operator-surface",
          [
            "Fast-map operator, CI, deployment, test, release, and background-job surfaces in {{repo}} for {{question}}.",
            contextInstruction(),
            "Focus: {{focus}}. Return concrete files, scripts, configs, missing areas, and candidate runtime bottlenecks."
          ].join(" "),
          fastOptions("Operator surface mapper", { resultCache: sourceContextResultCache() })
        )
      ]),
      parallel("Assess", [
        agent(
          "assess:risks",
          [
            "Assess the fast map for real P0/P1/P2 architecture and correctness risks.",
            "Separate confirmed risks, conditional risks, non-issues, and unknowns.",
            "Tie every important claim to inspected evidence and the invariants {{invariant}}."
          ].join(" "),
          fastOptions("Risk assessor")
        ),
        agent(
          "assess:runtime-speed",
          [
            "Assess runtime speed and user-wait risk for {{question}}.",
            "Look for serial agent work, repeated repository scanning, missing cache keys, oversized prompts, and long foreground jobs.",
            "Recommend mechanisms that preserve POLA, stdout/stderr discipline, and zero runtime dependencies."
          ].join(" "),
          fastOptions("Runtime speed assessor")
        )
      ]),
      phase("Verify", [
        agent(
          "verify:p0-p2-risks",
          [
            "Re-open evidence for every candidate P0/P1/P2 risk from the fast assessment.",
            "Confirm real risks, downgrade unsupported claims, and list exact file paths, commands, logs, or unknowns.",
            "The cw:result evidence array must cite durable locators."
          ].join(" "),
          strongOptions("Evidence verifier", { requiresEvidence: true })
        )
      ]),
      phase("Verdict", [
        artifact(
          "verdict:fast-synthesis",
          [
            "Synthesize a fast architecture verdict for {{question}}.",
            "Include a short answer, compact architecture map, ranked risks, speed recommendations, non-issues, and evidence links.",
            "State when the full architecture-review app should be scheduled as a background routine.",
            "The cw:result evidence array must support the final verdict."
          ].join(" "),
          strongOptions("Fast verdict synthesizer", { requiresEvidence: true })
        )
      ])
    ]
  });
};

function fastOptions(label, extra) {
  return taskOptions(label, FAST_MODEL, extra);
}

function strongOptions(label, extra) {
  return taskOptions(label, STRONG_MODEL, extra);
}

function taskOptions(label, model, extra) {
  return {
    label,
    sandboxProfileId: "readonly",
    ...(model ? { model } : {}),
    ...(extra || {})
  };
}

function modelHint(name) {
  const value = String(process.env[name] || "").trim();
  return value || undefined;
}

function contextInstruction() {
  return [
    "If {{sourceContext}} is non-empty, read that JSONL source context first and treat {{sourceContextDigest}} as its cache/digest hint.",
    "If the supplied context is missing, unreadable, or obviously stale, say so explicitly instead of guessing.",
    "If no source context is supplied, inspect {{repo}} directly."
  ].join(" ");
}

function sourceContextResultCache() {
  return { mode: "read-write", keyInput: "sourceContextDigest" };
}
