#!/usr/bin/env node
"use strict";
const cp=require("node:child_process"),crypto=require("node:crypto"),fs=require("node:fs"),http=require("node:http"),os=require("node:os"),path=require("node:path");
const root=path.resolve(__dirname,"..",".."),plugin=path.join(root,"plugins","cool-workflow"),cli=path.join(plugin,"dist","cli.js"),script=path.join(__dirname,"workbench-k6-deep.js");
const i=process.argv.indexOf("--report"),reportPath=i>=0?process.argv[i+1]:""; if(!reportPath) die("usage: node scripts/bench/workbench-load.js --report <path>");
function die(s){process.stderr.write(`workbench-load: ${s}\n`);process.exit(1)}
function digest(root){const h=crypto.createHash("sha256");(function walk(d){for(const n of fs.readdirSync(d).sort()){const f=path.join(d,n),s=fs.lstatSync(f);h.update(`${path.relative(root,f)}\0${s.size}\0`);if(s.isDirectory())walk(f);else if(s.isFile())h.update(fs.readFileSync(f))}})(root);return h.digest("hex")}
function fileHashes(root){const out={};(function walk(d){for(const n of fs.readdirSync(d).sort()){const f=path.join(d,n),s=fs.lstatSync(f);if(s.isDirectory())walk(f);else if(s.isFile())out[path.relative(root,f)]=crypto.createHash("sha256").update(fs.readFileSync(f)).digest("hex")}})(root);return out}
function passed(r,k){return r.metrics[k]&&Object.values(r.metrics[k].thresholds).every(x=>x.ok===true)}
function validate(r){if(r.schemaVersion!==1||r.benchmark!=="cw-workbench-load")throw Error("bad report");for(const s of r.stages)for(const p of ["http_req_duration","http_req_failed","checks"])if(!passed(r,`${p}{stage:${s.name}}`))throw Error(`threshold failed: ${p} ${s.name}`);if(!passed(r,"dropped_iterations"))throw Error("dropped iterations");for(const route of r.routes)if(!passed(r,`cw_route_requests{route:${route}}`))throw Error(`route not reached: ${route}`)}
function get(url){return new Promise((ok,bad)=>{const q=http.get(url,r=>{r.resume();r.on("end",()=>r.statusCode===200?ok():bad(Error(`status ${r.statusCode}`)))});q.on("error",bad)})}
(async()=>{if(cp.spawnSync("k6",["version"],{stdio:"ignore"}).status!==0)die("k6 is not installed");const work=fs.mkdtempSync(path.join(os.tmpdir(),"cw-workbench-load-"));let host;try{fs.writeFileSync(path.join(work,"README.md"),"# load proof\n");const plan=cp.spawnSync(process.execPath,[cli,"plan","architecture-review-fast","--repo",work,"--question","workbench load proof"],{cwd:work,encoding:"utf8"});if(plan.status!==0)throw Error(plan.stderr);const runId=JSON.parse(plan.stdout).runId;host=cp.spawn(process.execPath,[cli,"workbench","serve","--port","0"],{cwd:work,stdio:["ignore","pipe","pipe"]});const line=await new Promise((ok,bad)=>{let t="";host.stdout.setEncoding("utf8");host.stdout.on("data",c=>{t+=c;if(t.includes("\n"))try{ok(JSON.parse(t.split("\n")[0]))}catch(e){bad(e)}});setTimeout(()=>bad(Error("host start timeout")),10000)});const assets=fs.readdirSync(path.join(plugin,"ui","workbench")).sort().map(n=>`/ui/${encodeURIComponent(n)}`);const stateRoot=path.join(work,".cw"),before=digest(stateRoot),beforeFiles=fileHashes(stateRoot);const k6=cp.spawnSync("k6",["run","--quiet",script],{cwd:plugin,encoding:"utf8",env:{...process.env,CW_K6_BASE_URL:`http://${line.host}:${line.boundPort}`,CW_K6_RUN_ID:runId,CW_K6_REPORT_PATH:path.resolve(reportPath),CW_K6_UI_ASSETS:JSON.stringify(assets)}});if(k6.status!==0)throw Error(k6.stderr||k6.stdout);const after=digest(stateRoot);if(before!==after){const afterFiles=fileHashes(stateRoot);const changed=Object.keys({...beforeFiles,...afterFiles}).filter(k=>beforeFiles[k]!==afterFiles[k]).sort();const report=JSON.parse(fs.readFileSync(reportPath,"utf8"));report.changedStateFiles=changed;fs.writeFileSync(reportPath,`${JSON.stringify(report,null,2)}\n`);throw Error("Workbench changed .cw state")}await get(`http://${line.host}:${line.boundPort}/api/serve`);const report=JSON.parse(fs.readFileSync(reportPath,"utf8"));validate(report);report.stateUnchanged=true;report.postLoadServeStatus=200;fs.writeFileSync(reportPath,`${JSON.stringify(report,null,2)}\n`);process.stdout.write(`${JSON.stringify({benchmark:report.benchmark,stateUnchanged:true,postLoadServeStatus:200})}\n`)}finally{if(host)host.kill("SIGTERM");fs.rmSync(work,{recursive:true,force:true})}})().catch(e=>{try{const report=JSON.parse(fs.readFileSync(reportPath,"utf8"));report.runnerError=e.message;fs.writeFileSync(reportPath,`${JSON.stringify(report,null,2)}\n`)}catch{}die(e.message)});
